{{- if .Values.secret.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "prometheus-exporter-jdbc.secretName" . }}
  labels:
    {{- include "prometheus-exporter-jdbc.labels" . | nindent 4 }}
type: Opaque
data:
  {{ .Values.secret.key }}: {{ .Values.secret.password | b64enc | quote }}
{{- end }}
